### PR TITLE
Soft dice score

### PR DESCRIPTION
**Pull request by charleygros**
This PR replaces the hard `dice_score` by a soft version of it.
This implementation accepts both hard and soft input masks.
This partially addresses the issue #183.

Also, a new parameter `empty_score` --> returned value when both input array are empty. The default value is `np.nan`.

Example:
```
>>> import numpy as np
>>> import nibabel as nib
>>> from ivadomed.metrics import dice_score
>>> 
>>> soft_1 = nib.load('seg_soft.nii.gz').get_data()
>>> soft_2 = nib.load('seg_soft_masked.nii.gz').get_data()
>>> dice_score(soft_1, soft_2)
0.983514115962626
>>> 
>>> hard_1 = np.zeros(soft_1.shape)
>>> hard_1[soft_1 > 1e-3] = 1
>>> hard_1[soft_1 <= 1e-3] = 0
>>> dice_score(hard_1, soft_1)
0.9595146937789737
>>> dice_score(hard_1, soft_2)
0.9504741207898071
>>> 
>>> empty = np.zeros(soft_1.shape)
>>> dice_score(empty, empty)
nan
>>> dice_score(empty, empty, empty_score=1.0)
1.0
```

### CODE REVIEW

**Comment by jcohenadad** [comment]
About the proposition of setting a Dice score of 1 if both GT and predictions are empty: After googling around I found other groups using that approach:
- https://arxiv.org/pdf/1707.03237.pdf (see definition of DL2)
- https://www.kaggle.com/c/understanding_cloud_organization/discussion/114093
- https://stackoverflow.com/questions/47084179/how-to-calculate-multi-class-dice-coefficient-for-multiclass-image-segmentation

So i find it reasonable to give the option to set the output value to 1 (or nan or whatever) depending on the application.

**Comment by charleygros** [comment]
Add `import nibabel as nib` in `ivadomed/main.py`.

**Comment by jcohenadad** [comment]
> Add `import nibabel as nib` in `ivadomed/main.py`.

Because main.py is currently untouched in this PR, to prevent unnecessary conflicts, I suggest you rather add this line in this PR https://github.com/neuropoly/ivado-medical-imaging/pull/184

**Comment by charleygros** [comment]
> > Add `import nibabel as nib` in `ivadomed/main.py`.
> 
> Because main.py is currently untouched in this PR, to prevent unnecessary conflicts, I suggest you rather add this line in this PR #184

Better practice indeed. Will do a new PR as I dont know when #184 will be merged.

**Pull request merged**
