### PR TITLE
Data augmentation: exploration / optimisation tool

### LINKED ISSUE #255: Dev script: to visually optimise data augmentation parameters
So far, I have optimised my data augmentation parameters on fake data or by looking on TensorBoard the final result. I would find useful to visually see the result of a sequence of DA transforms on a MRI slice.

I would in particular use it for `ElasticTransform` where `alpha` and `sigma` are quite sensitive, `DialteGT`, `RandomRotation`.

Something like:
```
python show_transformation.py -i t2.nii.gz -c config_file.json --show-all-steps` -n 3
```
It would save in png the results of each transform (`--show-each-steps`) for 3 (`-n`) random slices of the input file (`-i`).

Could also work in 3D --> save each z_slice of a patch3D for instance?

### PR DESCRIPTION
**Pull request by charleygros**
## Aim:
Script to do some exploration / optimisation on data augmentation parameters.

## Changes
Create a script in the `dev` folder that:
- load an image (`i`)
- extract `n` slices from this image according to the slice orientation defined in `c`
- for each successive transforms defined in `c` applies these transforms to the extracted slices and save the visual result in a output folder `o`: `transform0_slice19.png`, `transform0_transform1_slice19.png` etc.

Example for a `CenterCrop`:
_CenterCrop_26

Note: this branch is based on `cg/move_config_to_rtd`.
Fixes #255.

### CODE REVIEW

**Comment by charleygros** [comment]
This tool aims at supporting us in optimising the Data augmentation parameters.

For instance, the parameters of `ElasticTransform` that are in the config files provide no visible data augmentation. See example: CenterCrop_ElasticTransform:
_CenterCrop_ElasticTransform_26__

Whereas after some optimisation:
_CenterCrop_ElasticTransform_26_

This optimisation should be considered for cases of over-fitting etc.

**Comment by jcohenadad** [comment]
these tools seem awfully useful! why not putting them inside a "utils-like" CLIs so they can be documented (and used)? if they end up in dev, i'm afraid nobody (except the developer) will use them

**Comment by charleygros** [comment]
> these tools seem awfully useful! why not putting them inside a "utils-like" CLIs so they can be documented (and used)? if they end up in dev, i'm afraid nobody (except the developer) will use them

That's a very good point.
It would be an opportunity to unearth other useful scripts from `dev` such as:
- `dev/compare_models.py`: stat tests on models performance
- `dev/convert_to_onnx.py`: pt --> onnx
- `dev/automate_training.py`: hyperparam model optim

Not too sure how to name the folder yet tho.

**Comment by charleygros** [comment]
Example:
```
python dev/visualize_transforms.py -i t2s.nii.gz -n 1 -c config.json -r t2s_seg.nii.gz
```
Screenshot 2020-06-11 21:29:11
```
python dev/visualize_transforms.py -i t2s_gmseg.nii.gz -n 1 -c config.json -r t2s_seg.nii.gz
```
Screenshot 2020-06-11 21:28:58

Note: I will add these illustrations to the RTD in a future PR, probably at the same time as #285.

**Comment by jcohenadad** [comment]
Fantastic @charleygros !!!

**Pull request merged**
