### PR TITLE
CI for documentation deployment

### PR DESCRIPTION
**Pull request by alexfoias**
Fixes https://github.com/neuropoly/ivado-medical-imaging/issues/248

### CODE REVIEW

**Comment by alexfoias** [comment]
@jcohenadad Can I open GH pages for this repo ? for the moment is off.

**Comment by alexfoias** [comment]
@jcohenadad Can I turn on GH pages for this repo ?

**Comment by jcohenadad** [comment]
> @jcohenadad Can I turn on GH pages for this repo ?

why would you like to do that?

**Comment by alexfoias** [comment]
Isn't the documentation of the project made using GH pages ?

**Comment by jcohenadad** [comment]
> Isn't the documentation of the project made using GH pages ?

https://ivado-medical-imaging.readthedocs.io/

**Comment by alexfoias** [comment]
Sorry, my mistake, I thought it was similar with shimming-toolbox.org
We don't need this PR, because this one is for GH pages. I'll do the change in namecheap.
This PR can be closed without merging.

**Comment by alexfoias** [comment]
@jcohenadad The change in DNS is made. We need 30min to propagate it. Sorry for the misunderstanding.

**Comment by jcohenadad** [comment]
changes out of scope

**Pull request closed without merging**
