### PR TITLE
Compute uncertainty

### PR DESCRIPTION
**Pull request by charleygros**
### In `cmd_test`:
- epistemic, ie DropOut augmentation
with:
```python
if context['uncertainty']['epistemic'] and context['uncertainty']['n_it'] > 0:
    for m in model.modules():
        if m.__class__.__name__.startswith('Dropout'):
            m.train()
```

- aleatoric, ie test-time augmentation
with:
```python
if context['uncertainty']['aleatoric'] and context['uncertainty']['n_it'] > 0:
    transformation_dict = context["transformation_training"]
else:
    transformation_dict = context["transformation_validation"]
```

- Loop across the `n_it` MonteCarlo simulations --> each sample is segmented `n_it` times, each 3D volume is saved `n_it` times (`*_pred_006.nii.gz`).

- call `combine_predictions()`
- call `voxelWise_uncertainty()`
- call `structureWise_uncertainty()`

### In `cmd_eval
- TODO: Post Pro --> will be done in a future PR, see issue #135.

### In config files:
- `"uncertainty": {"epistemic": true, "aleatoric": true, "n_it": 10}` 

### In transforms:
- TODO: undo_transform. Save params, then apply inverse transform?  --> will be done in a future PR, see issue #136.

### In `utils.py`:
- `combine_predictions` function averages the MS simulations to produce the soft segmentation (saved with `*_soft.nii.gz` suffix) then an argmax operator to produce the hard segmentation (saved with `*_pred.nii.gz` suffix).
- `voxelWise_uncertainty` function estimates voxel-wise uncertainty as entropy over all N MC probability maps, and saves results in `*_unc-voxel.nii.gz`.
- `structureWise_uncertainty` function estimates structure-wise uncertainty as IoU over the MC samples, coefficient of variation of the estimated volumes across the MC samples and average uncertainty, and saves results in `*_unc-iou.nii.gz`, `*_unc-cv.nii.gz` and `*_unc-avgUnc.nii.gz`, respectively.
- TODO: uncertainty-based filtering  --> will be done in a future PR, see issue #135.

### CODE REVIEW

**Comment by charleygros** [comment]
**Note: ** The slice-wise metrics (ie with `metric_manager`) are computed `n_it` times on each samples! --> We could discuss this aspect!

**Comment by charleygros** [comment]
Epistemic Monte Carlo simulation, with `n_it=4`, each color being one of the binary segmentations, preliminary experiments on the SpineGeneric dataset:
Screenshot 2020-01-29 22:41:46

**Comment by charleygros** [comment]
Convention: in the folder `pred_masks`:
- `*_pred_0x.nii.gz` --> MC simulation
- `*_soft.nii.gz` --> soft prediction (ie probabilistic) obtained from the MC simulations
- `*_pred.nii.gz` --> hard prediction (ie binary) obtained from the MC simulations

cf `combine_predictions()` from `utils.py` for more details.

**Comment by charleygros** [comment]
Screenshot 2020-01-30 17:36:45

**Comment by charleygros** [comment]
@charleygros : Reminder: can you move `combine_predictions` and `voxelWise_uncertainty` from `cmd_eval` to `cmd_test`?

**Comment by charleygros** [comment]
3 measure of structure-wise uncertainty:
- Intersection over Union: over all the N MC samples for a specific structure
- Coefficient of variation: for all MC volume estimates for a given structure
- Average voxel-wise uncertainty within the structure

**Comment by charleygros** [comment]
Note that I added a new config file: `config/config_sctTesting_lesionAx.json` with only isotropic or anisotropic with axial orientation data.

**Comment by charleygros** [comment]
Note: Intersection_over_union --> falls down to zero if one of the MC samples has not detected this lesion --> I am questioning if this metric is relevant for our task --> it would be however very helpful for tumour segmentation.

**Comment by charleygros** [comment]
Screenshot 2020-02-04 19:26:22

**Comment by AnBucquet** [comment]
> Note: Intersection_over_union --> falls down to zero if one of the MC samples has not detected this lesion --> I am questioning if this metric is relevant for our task --> it would be however very helpful for tumor segmentation.

What about computing the IoU only on True Positive?

**Pull request merged**
