### PR TITLE
Transfer learning

### PR DESCRIPTION
**Pull request by charleygros**
### Done
- `config`: add param `retrain_model` --> `null` if training from scratch, `path/to/pretrained-model` otherwise
- `ivadomed/main.py`: load pre-trained model
- `ivadomed/main.py`: freeze model weights
- `ivadomed/main.py`: replace `model.last_conv` and `model.last_film`
- `ivadomed/main.py`: filter out the params you want to fine-tune and send the remaining to the optimiser
- `testing/test_transferLearning.py`

### CODE REVIEW

**Comment by charleygros** [comment]
```
>>> from testing.test_transfer_learning import test_transfer_learning
>>> test_transfer_learning()
Using GPU number 1
Layers included in the optimisation:
	 decoder.last_conv.weight
	 decoder.last_conv.bias
1,147,009 total parameters.
577 training parameters.
```

**Comment by charleygros** [comment]
To run the testing function with FiLM:
```
test_transfer_learning(film_layers=[0,0,0,0,0,0,0,1], path_model='log_film/best_model.pt')
```

**Comment by AnBucquet** [comment]
Apparently `testing_data/model_unet_test.pt` is missing. I'll uppload one.

**Comment by AnBucquet** [comment]
Test failed when loading the model on `cpu`. Same problem with PR #114. working on it

**Comment by charleygros** [comment]
> Looks good to me! Thx @charleygros

Thanks for review
Let's wait for #114 merge :-)

**Comment by olix86** [comment]
Great! Added `retrain_model` to the config description in the wiki

**Pull request merged**
